### ISSUE TITLE
2.4 local mode crashing when offline 

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#100]
APK 2.4 seems to be crashing whenever it is utilized offline.  It will open offline, but as soon as the user tries to do anything (e.g. tap on a template), it will close. 

The team in Brazil brought this to our attention.  It is easy to replicate this bug:  

- open the app while the phone is online.  do any work on the app.  it should operate as expected.
- put the phone in airplane mode.  the app will close. 

This is a very debilitating bug.  Please fix ASAP and release a new APK.

**Comment by techteam25** [comment]
We already have a fix for it...  there are two other related bugs now:
1) we continually get a message when in Local mode and NOT connected to internet to "Check your internet connection and try again"

2) when in local mode and have approved the recordings AND already made the videos, if you reboot your phone or force quit the app you will NOT get to the locked phases without unapproving a slide and approving it again.

do you want them all fixed first?

@RobinRempel

**Comment by RobinRempel** [comment]
yes, please.  Fix all these.
