### ISSUE TITLE
Regionalize language names on the server for templates

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#101]
On the server, when a user goes to download more templates, it would be helpful for the users to see their language name in the script and form natural to them.  For the non-Roman script languages (like Khmer and Hindi_, you could put both the Regional script as well as the Roman alphabet name.  So these following could be changed/added:
Français
Español
Português
Bahasa Indonesian
KiSwahili
हिंदी Hindi
ខ្មែរ  Khmer
తెలుగు  Telugu

**Comment by tkmeadows** [comment]
This is both on storypublisher.website and on the SPadv app now.  I think this is done.
