### ISSUE TITLE
Add a numerical passcode for story approval

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#103]
In order to make it easier for Accuracy Checkers working in nonEnglish languages, we want to add an approval passcode/password in the Accuracy Check phase that uses numbers.  This will help non English keyboard users (e.g. Hindi or Khmer keyboard users) to not have to change their keyboard in order to approve a story.  
This number password will be hardcoded **in addition** to the current hardcoded password.  
So, the result will be that end users (Accuracy Checkers) can use either the current letter password or the (new) number password to approve a story and to unlock the last phases of a story.
The additional number password will be:  2777683  (seven numbers)

**Comment by tkmeadows** [comment]
this was done early summmer
