### ISSUE TITLE
Copyright for stories 001 through 099

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#104]
There are several different copyrights for the stories less than 100.  Robin has slides for them all made up that she inserts into the PS3 cab file.  We need to adjust the PhotoStoryToBloom conversion utility so if the slide is 99 or less it does not insert the copyright text into the story.json file and it does pass along the copyright slide, then we need to adjust SPadv so if the story is 99 or less it uses the copy slide (last slide) instead of creating it from a blank one with text.

**Comment by tkmeadows** [comment]
This has been done in our new PhotoStoryToBloom conversion utility
