### ISSUE TITLE
UI updates for v2.6 release

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#105]
The following language UI files have recently been updated or finished and are ready to be attached to the v2.6 release:

- English WordLinks (many typos corrected)
- French WordLinks (all columns now translated)
- French strings
- French help docs
- Bahasa help docs
- Bahasa wordLinks (columns BCF)

all these files can be found here: 
https://drive.google.com/drive/folders/1Ovv7_qDSTOjiM8WYlObnj7er8snkJsN7

**Comment by techteam25** [comment]
Is this a full list as compared to #99?

**Comment by RobinRempel** [comment]
Yes, I've just updated the list today.  (more gateway language resources
are now available to be utilized).

Robin
