### ISSUE TITLE
Change font size on Title & Song slides

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#106]
Since non-roman scripts often take up larger space and/or their words can be longer, make a way to adjust the font size on the title and song slides.  Example of one idea of how this may look is attached.   Temporary fix was to change the following line from 32 to 24 in SlideViewModelBuilder:  
SlideType.FRONTCOVER, SlideType.ENDPAGE -> 24

![fontsize-idea](https://user-images.githubusercontent.com/54723877/233127911-5b08d1a1-af5e-4784-a531-82e8210302d6.png)

**Comment by tkmeadows** [comment]
this was done early summer...
