### ISSUE TITLE
story text (in Voice Studio) not auto-saving

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#108]
In a recent virtual training on SPadv using v 2.12, a user in India complained that she lost all the story text that she had been typing into the Voice Studio when she got a phone call and exited the app (probably not closing the app, but using another app while SPadv continued to run in the background). After her phone call, she came back to the app and realized that she had lost all the text that she had typed on each slide. She had to retype her whole story. She requested that the app would auto-save story text on each slide when the user navigates of that slide (just like the audio auto-saves). 

As a temporary "fix", I suggested that when she uses the SPadv app she put her phone into airplane mode or disconnect from wi-fi so she doesn't get interrupted and lose her data. 
Probably this is another issue, but would there be a way that SPadv could over-ride or not allow alerts from other apps to interrupt them while they are audio recording?

**Comment by tkmeadows** [comment]
I have easily duplicated this issue on ANY of the phases with the text tool on it.  Simply add/change text in the field, hit save, force quit the app, call it back up and the text is not there.  As long as you change the phase, hit play, OR hit record/stop the text will be saved.
