### ISSUE TITLE
Remote approval not show on app

### ISSUE THREAD

**Issue by tkmeadows** [techteam25/SPadv#16]
The approvals do not come down to the phone app if the user is sitting on the list of templates when the approval is done on ROCC.  If start from app not running OR when in the story it seems to work fine.

**Comment by RobinRempel** [comment]
I tested this with v2.2 and ROCC did eventually successfully approve the SPadv story.  However, if both the SPadv user and the ROCCer are both messaging/online at the same time, sometimes page approvals get undone in SPadv even tho they show approved in ROCC ... this seems to happen when the ROCCer refreshes the screen.  So, it's showing approved in ROCC, but in SPadv, some pages are not showing approval.  The SPadv user would have to manually communicate to the ROCCer which page is not approved and then the ROCCer must redo the approvals for those pages.
