### ISSUE TITLE
Mentor or multiple consultant

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#17]
Would like to have a way for a mentor/trainer to be able to see stories of consultants under them, and/or have multiple consultants be able to view the same stories on ROCC.

**Comment by techteam25** [comment]
The ability for multiple consultants is manually possible by going into ROCC, then Admin, then under "Assign Consultant" select the Consultant and Project, then click on "Assign" on that same row.

Of course, this does not allow for one consultant to be a mentor/backup/etc for another consultant.

@RobinRempel

**Comment by RobinRempel** [comment]
This is good enough.  Closing.
