### ISSUE TITLE
upload all SPadv templates to server and add download messages

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#20]
After modifications and copyright changes have been made to SPadv templates, upload all templates to the server for direct download to a user's SPworkspace folder. 

Consider to add some messaging during the template downloads to communicate with the user when downloads do not take place as expected, such as:

- internet connectivity is not adequate, bandwidth is insufficient or there is no connection to the internet
- storage space in the workspace folder is not enough (.5 GB is needed to process 1 template, on average)
- consider to download fewer templates due to slow internet
- add the "000" demo template to the ROCC templates so available to ROCC user for approving??
  (get error message now and not able to upload audio of it)

**Comment by tkmeadows** [comment]
This has been done over time and parts were duplicated in other issues.
