### ISSUE TITLE
change copyright statements on all templates

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#21]
Programmatically make copy-paste changes to copyright and acknowledgment licensing statements on all the templates according to this document
[copyright changes for SPadv templates Sept 2022.pdf](https://github.com/techteam25/SPAdv/files/9659122/copyright.changes.for.SPadv.templates.Sept.2022.pdf)

**Comment by RobinRempel** [comment]
https://docs.google.com/document/d/1XXH7XJI1NCobVVjjyK6vKfxa8UqZW2rmgEdCvyPh9cU/edit?usp=sharing
 updated link for info to change

**Comment by tkmeadows** [comment]
In the html file for all SPadv bloom & bloomsource templates...

make changes as described in:
\\10.10.10.247\csdept\StoryProducer\Documentation\SPadv copyright changes.docx
