### ISSUE TITLE
Modify all templates with number of slides in the title

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#22]
Modify all templates by adding the number of slides in a template i.e. ##s to the ### Gateway language title
This is row T on .doc scripts and front page/cover in .bloom scripts

Examples:
1.	002 Lost Coin    6s
2.	114 Joseph Forgives    66s
3.	221 Jairus Trusts    20s
4.	224 Yesu Analisha 5000   17s
5.	266 Pablo en Éfeso   13s

**Comment by tkmeadows** [comment]
I do not see us putting the count actually on the title in the json file, rather dynamically putting it on the title as we display it, that way the count should never be wrong.

So, what screen(s) do you want the slide count to show beside the title?
- Rocc side bar?  
- Rocc heading over story approval?
- SPadv list of available to download ?
- SPadv list of downloaded?

@RobinRempel

**Comment by RobinRempel** [comment]
So, what screen(s) do you want the slide count to show beside the title?

   - Rocc side bar? * Not necessary*
   - Rocc heading over story approval?  *Not necessary*
   - SPadv list of available to download ?  *Yes, this*
   - SPadv list of downloaded?  *Definitely this*

**Comment by RobinRempel** [comment]
slide numbers are working well, showing up well, even for new templates I upload, the slide numbers show up.  Closing.
