### ISSUE TITLE
Some images not present

### ISSUE THREAD

**Issue by tkmeadows** [techteam25/SPadv#23]
When a user downloads more templates, sometimes some or all of the images have 0 bytes and thus show nothing.  Dan had the issue once, Robin had it on 5 phones, I duplicated it on the Samsung tablet once... but then could never get it to fail again.

**Comment by tkmeadows** [comment]
Thought it may have to do with multiple phones downloading at the same time, or slow internet, or having just created the workspace folder, or selecting multiple larger templates... but trying those variations did not seem to make a difference in duplicating the issue.

**Comment by RobinRempel** [comment]
with v2.2 this issue seems to be cleared up.  templates are all downloading properly, even when many are selected at one time . Closing.
