### ISSUE TITLE
update ROCC icon 

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#25]
![image](https://user-images.githubusercontent.com/98855936/190056421-6fe64ce6-86af-4535-be7d-f4381f1a12f3.png)

As you can see from this small screen shot, the tiny icon that is displaying for ROCC shortcut and URL tabs is outdated.  

@tkmeadows

**Comment by RobinRempel** [comment]
I refreshed the website etc, but am still getting this "old" icon showing up as a tiny thumbnail.  Move this card back to "To Do" ?

@tkmeadows

**Comment by tkmeadows** [comment]
Or clear your browsing history and try it again?

Tim

**Comment by RobinRempel** [comment]
Done. Thank you!. Closing.
