### ISSUE TITLE
Registration screen to appear until submitted

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#27]
With the 1.1.7 debugger installation changes, we lost the Registration screen being on the "surface" to  annoy the user until they fill and submit it.  I would suggest that the Registration screen should appear every time "download more templates" is requested until the Reg is submitted at which time it can "hide". 

@tkmeadows

**Comment by tkmeadows** [comment]
Is the registration to be skipped when they go to templates in the future no matter how little they enter in the registration?  They enter only their name?  What if it is remote instead of local?  Are there minimums of what need entered based on local vs remote?

@RobinRempel

**Comment by RobinRempel** [comment]
This is working properly now as of 1.1.8.  Closing.

**Comment by RobinRempel** [comment]
Yes, Reg can be skipped/hidden no matter what fields have been filled, so
long as they submit it.
