### ISSUE TITLE
Installation prompt changes

### ISSUE THREAD

**Issue by tkmeadows** [techteam25/SPadv#29]
Change the initial prompts upon install to create workspace folder, then how the list of templates.  The user can go back to the menu for registration and downloading more templates as needed.

**Comment by RobinRempel** [comment]
What you did for 1.1.7 debugger is much better than what we had before!  Nicely done!
Here are a few edits to make to the Welcome screen:
- remove "and other assets" 
- remove the demo button (lower left corner)
- change "pressing" to "tapping"

@tkmeadows

**Comment by RobinRempel** [comment]
Done.  Closing.
