### ISSUE TITLE
1.1.4 app crash when moving from Community to Story Tell Back

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#31]
1.1.4 debugger app always crashes when trying to swipe from the Community Work phase to the remote series of phases, specifically to Story Tell Back.  Once the app crashes, I cannot get back into a story in progress.  I can access a unstarted story, but it seems that the story.json file gets corrupted.
Sometimes the app does not crash when the drop down menu is used to move into remote phases, but it seems to not crash only when phases are skipped.  If you proceed from phase to phase in order swiping or tapping the dropdown menu, it seems to crash (and corrupt the story.json file).  So maybe the bug is just in moving from Comm Work phase into the remote phases.  I've also noticed that once the user has moved into the remote phases, then you can move back to Trans + Rev or Comm Work by swiping or tapping menu and no crashing occurs.
@dharding1958 @tkmeadows

**Comment by RobinRempel** [comment]
- install 1.1.4 afresh on my 11 phone to new SP workspace folder
- fill out minimal info in Registration (lang name, ethno code, cons name and email, remote location) and submit. 
- don't actually send anything by an app.  cancel. tap CONTINUE button.
- **app crashes**
- reopen app
- open Lost Sheep
- record in Learn.  
- swipe to T+R phase
- in T+R record for each slide, not song slide
- swipe to Comm Work
- play a few slides
- swipe down (to go to Story Tell Back)
- **crash**
- reopen app
- open Lost Sheep template
- swipe to Comm Work. swipe down to Story Tell Back
- **crash**
- reopen app. 
- open Lost Coin
- play and record in Learn
- swipe to T+R
- record a translation for each slide, not song slide
- swipe to Comm Work
- swipe back to T+R
- tap menu to Story Tell Back
- **crash**
- reopen app
- tap on Widow's Gift to open
- swipe to T+R
- record audio for each slide, including song slide
- tap menu to Story Tell Back
- **crash**

**Comment by techteam25** [comment]
Thanks for the good, step-by-step of what you did.  I followed it completely, starting with a fresh download of the 1.1.4 debug apk, load the templates, recording the Learn and T&R slides, etc... and cannot duplicate the problem.  I tried it on:
- Android 12 phone
- Android 9 tablet & phone
- Android 11 emulator in Android Studio

Is the Android 11 the phone that you use?  Could we have it here for an hour or so to see if it will fail while plugged into our system in debug mode?

@RobinRempel

**Comment by tkmeadows** [comment]
On Robin's phone we found that it only happens when there is a recording for the title slide, and it does not happen on other phones.  Her phone was a motorola with .5mb (or less) memory free.

**Comment by tkmeadows** [comment]
Duplicated the crash, remove Title recording, is fine, put back and and crash.   Used a 4" WVGA Nexas S with API 30 on Andriod Studio emulator.

**Comment by tkmeadows** [comment]
This is very intermittent on our emulator.  Too difficult to reproduce for us.  I suggest we either take it off out the issue board or you drop that phone off to us so Dan can work with something that fails consistently for a COUPLE DAYS.

**Comment by tkmeadows** [comment]
From Robin on debug 1.1.7 tested on both android 7 and 11:
No title slide recording crashing issues so far  :)

**Comment by RobinRempel** [comment]
this seems to no longer be a problem.  everything is testing good with v2.2.  Closing.
