### ISSUE TITLE
1.1.3 debugger crashing

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#34]
When trying to beta test issues techteam25/SPadvR3#85, techteam25/SPadvR3#50 and techteam25/SPadvR3#40 with a clean slate on my Android 11 phone, with a new install of 1.1.3 debugger, I encountered a lot of crashing.

1. 001 Widow's Gift.bloomSource template seemed to scan and open properly in the app.  But when I left a comment in Community Work phase, the app crashed and I could not get back into this story
2. I opened 003 Lost Sheep template and started going through the phases, but I skipped Community Work phase intentionally.  I did Story Tell Back and sent the audio file to ROCC.  Then I did the Slide Tell Back phase and sent all the audio files, tho for a couple slides I did not wait to see the tick mark appear in the cloud. When I swiped down to Remote Check, the app crashed and would not let me back into that story when reopened.
3. I opened ROCC to see what was there.  Dan said that he had cleaned out everything, but when I opened my account, several old stories were obviously still present.  Snake story and Lost Coin were there and Widow's Gift was there, completely approved (so this was from before).  Lost Sheep was also there, but it was an old version from before because it already had some messages in it.  

I cannot do any further reliable testing until (1) my ROCC accounts gets cleaned off completely, and (2) preferably, I get a new debugger build.  
@dharding1958

**Comment by RobinRempel** [comment]
I have just finished a test on my Android 8 phone with Widow's Gift.bloomSource after everything got truly cleaned off of ROCC so there was a clean slate on all aspects (as per Tim's notice).  And everything worked perfectly, no crashing, proper presentation in ROCC.  :)  
I can return to my Android 11 phone and redo the test now that ROCC got cleaned up. 
A couple notes about two minor bugs:

**Observations on the multiplying messages in this test run:**

- Only the first message sent from ROCC (title slide) to SPadv was multiplied on SPadv (it duplicated twice, as two)
- subsequent messages sent from ROCC (title slide) to SPadv were not duplicated
- All other messages sent and received on all other slides presented as single messages, as proper, as expected.
- Ah, but after I closed the app and opened it again, or after I went back to the Remote Check phase after finishing a video, I noticed that **all** the messages in SPadv had duplicated/doubled.  (Messages in ROCC all remain single and stable.)

**Title slide text black background bug:**
The black background does not properly sync with the white letters, especially if the text line is long and goes from edge to edge of the screen. It seems to sync better with shorter text lines. See screen shots:
![Screenshot_20220819-133701](https://user-images.githubusercontent.com/98855936/185690989-e027a1fa-34b9-436f-8abc-e8ce639f97ae.png)

![Screenshot_20220819-133728](https://user-images.githubusercontent.com/98855936/185690871-d5507a9b-b124-49c1-af89-96a37dc9c05d.png)
m/98855936/185690862-dede216a-4efc-499f-8d22-4964c495fd05.png)

@dharding1958 @tkmeadows

**Comment by RobinRempel** [comment]
1.1.3 on my Android 11 is still crashing, even after reboot, reinstall and clean workspace folder. It is a second device using the same consultant as my Android 8 device that worked properly.  It's crashing swiping out of Community Work phase and not allowing me back into the story I started working on when it crashed. 
@dharding1958 
@tkmeadows

**Comment by techteam25** [comment]
Just to be sure I have all the facts I may need to try to duplicate the issue:
Different phone
Different language **RR: same language**
Same consultant
Same story **RR: different story (than what I used for testing on Android 8 phone)**

Right?
@RobinRempel 
@dharding1958 @tkmeadows

**Comment by techteam25** [comment]
The android 8 crashing was resolved,
the android 11 crashing is now duplicated on techteam25/SPadvR3#31,
the title text outline cannot be duplicated on our devices,
the ROCC issue was our problem only cleaning the database records and not the files for the project/story,
the multiplying messages is issue techteam25/SPadvR3#43 - not here

It is easier and cleaner for an issue to have just one item, and to keep everything about that issue in that item...

@RobinRempel
