### ISSUE TITLE
Update Registration Help doc with remote notes 

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#37]
I'll put a few points to insert into the Help doc here, when I get around to it.

**Comment by RobinRempel** [comment]
Registration Help Doc edits needed:

3. put a space before **SUBMIT**
4. change "...3-bar ..." to "3-lines menu icon"
7. delete "... and to" after the email address in both point 7 and also in the bullet under point 7

Change **Consultant Information** subtitle to **Accuracy Checker Info**:

Edit the last bullet point to read like this:

- **Location type** dropdown menu - This menu choice is a switch to determine the app phase interface.  **Local** is the default.  Choose **Local** to keep a 7-phase offline interface.  **Local** assumes there is a local Accuracy Checker who will approve stories on-site or in-person.  Tap **Remote** to switch to a 9-phase interface enabling digital back translations and communication between the translator(s) and the remote consultant.  **Remote** assumes that the Accuracy Checker (Consultant) will approve stories via remote control using the ROCC (**R**emote **O**ral **C**onsultant **C**hecker) web app.  **Remote** mode requires some minimal internet connectivity capacity so that audio and text files can be sent and received by the SPadv app and the ROCC web app.  To assign and connect a SP language project to a ROCCer, the ROCCer's contact info must be registered in the ROCC and the SP registration here must be filled out with the ROCCer's same contact info and then submitted online.
- Note:  

Notes: 
-  If a SP language project starts off in **remote** mode and matures in capacity to have a **local** Accuracy Checker, the Registration **Accuracy Checker Info** drawer can be updated, the Location type can be changed to **Local**, the app interface will change, and story production can continue on with the local Accuracy Checker approving stories.  Do not switch between **Remote** and **Local** in the middle of completing a story.
- The ROCC web app login via a browser can be accessed from the [StoryProducer.website](https://sites.google.com/view/spadv-website/home?authuser=2)

@dharding1958

**Comment by RobinRempel** [comment]
This looks good now.  There is one extraneous Note bullet under the Location Type bullet which could be deleted.  (Robin's typo.)  Then this issue can be closed.

**Comment by techteam25** [comment]
This has been corrected...
