### ISSUE TITLE
sync/update project link

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#4]
If multiple devices were being used to translate and create videos in one language project, it would be helpful to have a way to update and sync the multiple devices.  
Purposes: 
(1) to enable more devices to share available videos; 
(2) to mitigate against duplicating work

Suggested UI/UX: 
(1) when the devices are in close proximity to each other, tap a "sync devices" link in the main side bar menu and the SPworkspace folder in each device adds the [video] files for all completed stories that the other device does not have via bluetooth (? very slow!) or another syncing app that can be utilized offline.  
(2) if devices are remote from each other but online, how could they sync?

**Comment by tkmeadows** [comment]
This is one of the purposes of the backup/restore/delete feature in a different issue that has recently been completed.
