### ISSUE TITLE
ROCC not allowing approval of stories due to 1 too many slides

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#40]
with the Aug 6 update, ROCC is not allowing a story to be approved and unlocked because it thinks there is always one slide left unapproved (even when all slides have been approved).  
For example, in reality the Lost Coin story has 7 slides (including the title slide #0 and the song slide techteam25/SPadvR3#85), but ROCC thinks the Lost Coin story has a total of 8 slides that need to be approved.  (Maybe it is counting the un numbered copyright/acknowledgment slide).  Therefore, the ROCCer can never unlock the Lost Coin story for the SPadv user because the ROCCer cannot get to the last slide that ROCC thinks is unapproved.
![Screenshot (29)](https://user-images.githubusercontent.com/98855936/183471896-09da5667-7333-469a-8fb2-006ce487d329.png)

**Comment by techteam25** [comment]
I added code to UploadSlideBackTranslation.php to skip adding the copyright slide into the slide table on ROCC.  This should allow 100% to show when all slides needing approval are approved.   The creating of the video did not seem hampered on the app, ROCC just wasn't showing the right percentage.

**Comment by techteam25** [comment]
ROCC has been fixed so the copyright slide is not included in the 'slide' table and also not in the calculation of "everything" being approved.

**Comment by RobinRempel** [comment]
@dharding1958 
while testing 1.1.3 debugger on remote mode , in a fresh workspace folder, I seemed to be getting lots of app crashing when trying to navigate to the song slide.  I started with Widow's Gift template and ROCC had approved all slides, but rSPadv was not showing the approvals.  
Does SPadv have to be online at the same time as ROCC is approving a slide for the approvals to take place on SPadv?  
After crashing with Widow's Gift template, I tried testing with Lost Coin and Lost Sheep templates, but eventually I could not even open a story, everything was crashing.  Even after a phone reboot.

**Comment by RobinRempel** [comment]
@dharding1958 
with all fresh workspace folder and fresh ROCC dashboard, I tested 1.1.3 debugger on11 Aug and now ROCC is approving the SPadv story!  Yea!  
However, on ROCC, the progress circle for the approved and finished story is showing that there is still one unapproved slide.

**Comment by techteam25** [comment]
@RobinRempel 
If you do this from the clean slate it should work fine.  It was an issue only when the ROCC database had entries in it prior to our fix.

**Comment by tkmeadows** [comment]
closed based on conversation with Robin when she was in the office... that this works now.
