### ISSUE TITLE
Tell back text send airplane icon should be white 

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#41]
for the rSPadv 1.1.2 build, in the Slide Tell Back phase, the paper airplane icon for sending text back translations to ROCC (and which also display in rSPadv Remote Check phase) is not consistently displaying the correct color.  It should always be white and when text has been sent it should turn blue.  Often I see a blue airplane on slides where no text has been sent.
When any sent text is edited, the icon should refresh to being white.  This action seems to be working consistently.

**Comment by techteam25** [comment]
the first time into the slide tell back it all looks and acts correctly, but when you scroll to the next slide then back to the one with the text that was already sent THEN the arrow is the wrong color

**Comment by RobinRempel** [comment]
@dharding1958 
for 1.1.3 debugger the Slide Tell Back text airplane send icon -- the color is still very confused.  It should be white by default and then turn blue when a text has been sent.  The icon should return to white if the text is edited, and then turn blue again when a (new) text is sent.  ... This for each individual slide.

**Comment by RobinRempel** [comment]
upon testing with 1.1.4 debugger, the color of the airplane icon seems to be correct now.  Closing issue.
