### ISSUE TITLE
multiple copies of remote check text messages

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#43]
for the rSPadv 1.1.2 build, the Remote Check phase is displaying multiple copies of text messages.  These multiple copies of messages seems to reduce back to a single copy when the user reboots the app (so the workspace folder is scanned again). 
The ROCC is displaying text messages properly (one copy each)
![Screenshot_20220806-144950](https://user-images.githubusercontent.com/98855936/183460824-61ae5ded-a7fe-4120-8e34-f977d27a0058.png)
.

**Comment by tkmeadows** [comment]
I think this no longer happens.  I used to be able to make it fail but have tested it many times and cannot duplicate it now.   8/26

Got it to fail yesterday, today I cannot duplicate it.  Too hard to consistently get it to fail.   9/2

**Comment by tkmeadows** [comment]
This is very intermittent for us.  We need to have an exact tap-by-tap that makes it happen every time or just move it off the list until someone stumbles onto the trigger that makes it fail consistently.

**Comment by RobinRempel** [comment]
Your suggestion to move this off the list until... is ok with me.  It's not a blocker bug.  Maybe I'll bring my 7 phone to you next week to work on if this issue arises with other new users. 
@tkmeadows

**Comment by RobinRempel** [comment]
Multiple messages seems to not be occurring now as of debugger 1.1.13.  Closing.
