### ISSUE TITLE
Slide Tell Back audio upload fails for Droid 8

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#45]
When testing the Aug 6, 2022 update of ROCC and the rSPadv 1.1.2 debugging on my Android 8 phone, all the slide tell back audios (including title slide) failed to upload.  Everything worked fine for my Android 11 phone.

**Comment by RobinRempel** [comment]
This is still an issue for 1.1.3 debugger on my droid 8 phone.  Audio uploads are working for my Droid 11 phone, so maybe this is not a high priority fix.  Mostly likely, if we starting using remoteSPadv in the field, we will be using newer phones (i.e. Android 10 or higher/newer)

**Comment by LucasAtTECH** [comment]
We have the audio upload working on an Android 7.1.1 device.

**Comment by RobinRempel** [comment]
And the audio uploads as it should for my Android 8.1 device too.  Well done on the fix.  Closing this issue.

**Comment by RobinRempel** [comment]
Great! Let me test again on my droid 8
