### ISSUE TITLE
ROCC - welcome screen color issue

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#48]
All of the ROCC logo is not showing up well on the dark background color -- the black "ROCC" text of the logo in the legs area of the rocking chair is almost invisible.  Suggest to change the dark background theme color to a lighter lavender color.  This would also make the black background of the thumbnails in the story view show up better.  Or, change the gradient to be lighter on the left.

**Comment by RobinRempel** [comment]
From testing Aug 7 2022 build with rSPadv 1.1.2, this bug has been dealt with.  Issue can be closed.
