### ISSUE TITLE
Change the interface language in SPadv

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#49]
We want to be able to change the interface language of SPadv from English to French, Portuguese, Spanish, Indonesian?, Cambodian etc.
Maybe all the strings (all the various messages and help docs) do not need to be translated, but at least the phase labels, the menu options and major place holding texts.  
We shall attempt to translate the Strings via NotePad++ (translating all the black font text).  

Translated strings files can be accessed from [this Google folder called Strings](https://drive.google.com/drive/folders/1OdyC6u1Q3TBEyr4XXKCP7H4HVe9BAvIx?usp=share_link)

Another aspect to this issue is to write the code and develop the UI/UX for changing the app's interface language when installing the app.  Dale should be involved in this as he has some insights from past experience.

**Comment by tkmeadows** [comment]
Another step to this is eliminating all the hardcoded text that remains in SPadv, which is already in an issue techteam25/SPadv
