### ISSUE TITLE
bugs for remSP(xml) Slide Tell Back phase

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPAdv#5]
using/testing the apk from Jun 14th

The title slide seems to not want to upload to the server.  The message says the audio file is in progress of sending, but the cloud icon never gets a check mark like the other slides; the cloud icon stays light blue with the up arrow.  Maybe it doesn't know where to go because I've not put in the ROCC URL?  But the other audio files seemed to have been sent. 
- the audio appears to get uploaded fine, it seems the fix is to update the indicator/check as is not getting put onto the first slide

**Comment by techteam25** [comment]
seems to work in our testing

**Comment by RobinRempel** [comment]
I think this issue has been dealt with.  Closing
