### ISSUE TITLE
add ROCC About info

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#52]
ROCC needs to have an About menu added (to the dashboard?).
Info that should be accessible from the About menu can include:
- **version number of the build**
- **preference for use with SPadv version number?**
- **copyright/ownership statement** [The Remote Oral Consultant Checker for StoryProducerAdv (ROCC4SPadv) software is jointly copyrighted (c) by Tyndale Bible Translators and Robin Rempel, 2022.]
- **acknowledgment of contributors** [Acknowledgment and much gratitude is extended to three teams of senior software engineering design students and their professors-advisors from Cedarville University, USA between the years of 2016-2020 for their generous contribution of building and developing ROCC prototype code and user interface along with the necessary corresponding prototype code and user interface utilized in the Story Producer app (SP app), remote version, and setting up the server system that interfaces between ROCC and SP app.  Much thanks to God is also extended for the graphic artist and software engineering professionals and interns at Tech Team Advantage for their significant contributions in rebasing, updating and maintaining the ROCC and StoryProducerAdv (SPadv) software so that the Bibleless ethnic groups of the world might be able to help themselves have access to God's Word in their own languages.]
- **license/permission info** [The Remote Oral Consultant Checker for StoryProducerAdv (ROCC4SPadv) web app is released under the following license: Permission is hereby granted, free of charge, to any person lawfully obtaining a copy of this software and associated documentation files (the "software") to use and redistribute the software, to build and distribute videos from text and audio-visual data, provided that the are the owner of the data or have permission to distribute it.  The Software is protected by international copyright treaty provisions.  No person may remove any copyright or other proprietary notice from the software nor reverse engineer, decompile, or disassemble the software.  THE SOFTWARE IS PROIVED "AS IT", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNES FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABLITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OF THE USE OR OTHER DEALINGS IN THE SOFTWARE.]

**Comment by RobinRempel** [comment]
This issue can be closed as soon as a proper copyright symbol  © is inserted into the text to replace the (c) in the first line.

**Comment by techteam25** [comment]
I changed the symbol and  the issue.
