### ISSUE TITLE
Easier installation of app and templates.

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#54]
Ideas for reducing the need for manual android file management:
- upon installation, SPadv app will automatically create a 1SPworkspace folder -- by default in the root of the internal storage, or user can manually choose the root of the SD card (use radio buttons to show the default and option)
- download templates directly into the 1SPworkspace folder.
- when the app scans for .bloom templates (either when asked by the user or whenever the app is opened afresh), it scans everywhere on the phone and pulls any .bloom or .bloomSource file (maybe the unzipped folder version) into the 1SPworkspace folder.

**Comment by RobinRempel** [comment]
The 1.1.6 debugger UI/UX looks and works nicely.  Thank you!  Are those downloading from the SPadv google My drive?

Now the welcome screen(s) need to be modified for easier installation for first-time users. I've made a draft of some screen [here](https://docs.google.com/document/d/1TJ7VBv2pa9I6Y2IcfJJ2Wf30QQHP-qfkrIQOknPHizw/edit?usp=sharing) which I hope you can work off of.  I put the draft notes on a google doc thinking it would be easier to comment and polish the wording and the navigation.  

@tkmeadows @dharding1958  @DaleHensley

**Comment by tkmeadows** [comment]
creating a folder at the root level is not possible.  The rest of this in done.
