### ISSUE TITLE
Registration for remote is not allowing manual sharing

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#59]
In the SPadv v1.1.1 debug, with Registration location setting on 'remote', it seems that when the 'submit via' button is tapped, there is an automatic connection to the ROCC (which is good), but the user is not allowed to choose any app (e.g. gmail, whatsapp, bluetooth, messenger) to utilize for sending all the Registration info to the various contacts listed in the Registration fields.  It seems that there is no means by which all the Registration info can be sent to the Reg contacts (for the purpose of an analytics database).

**Comment by techteam25** [comment]
To us it looks like Cedarville never wrapped up that part of this.  In his demo Phillip never actually selected an app, he tapped elsewhere to "cancel" or avoid sending.

Where is the data supposed to be submitted?
- Into a database?
- To Firebase analytics?
- to your email?
- to a Google Sheet?
- somewhere else?


You say "all the registration info"...   you literally mean every field in all areas of the registration screen?

**Comment by LucasAtTECH** [comment]
I have added a continue button to give the user time to submit their registration.
The changes in the code were made to reload the templates to fix bugs when changing from local to remote and vice versa.
Let me know if I can close the issue now or if more changes are needed.

**Comment by RobinRempel** [comment]
Let's test the debug in a new APK build and then close the issue if all tests out well.

**Comment by RobinRempel** [comment]
With the  rSPadv 1.1.2 build, this issues seems to be resolved. Closing the issue.
