### ISSUE TITLE
edit the Slide Tell Back phase banner bar color and icon

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#65]
The icon for the Slide Tell Back banner bar should be changed to something that is similar but different from the Story Tell Back phase icon.   Here is a draft idea:
![Slide tell back icon1](https://user-images.githubusercontent.com/98855936/181996157-e2f72448-fbbd-4bb1-b287-9cc6bbb8206f.png)
Also, the color of the phase bar should be changed because it is too similar to the Voice Studio phase color.  Maybe change the color to a dark mustard yellow (?)  (Maybe ask a graphic artist for ideas, considering the colors of the other phases)
![Slide tell back phase color](https://user-images.githubusercontent.com/98855936/181996378-206633b0-d164-4b88-a7af-a3674ac7ad29.png)

**Comment by techteam25** [comment]
We are limited with icons to those in the android.drawable.seticon stuff

**Comment by RobinRempel** [comment]
For rSPadv 1.1.2 debugging build, the updated icon is ok, but I think the phase bar color is too light (the white text labels on the banana color does not show up very well.  Let's try for a darker mustard color like this:
![Slide Tell Back color darker](https://user-images.githubusercontent.com/98855936/183447894-206ed709-8269-4e57-b23e-246fa64431c3.png)

**Comment by techteam25** [comment]
color has been changed to #c09100 for the next debug version

**Comment by RobinRempel** [comment]
tested in 1.1.3 debugger.  Looks good!  Closing.
