### ISSUE TITLE
Story Tell Back file upload is failing

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#66]
When a SPadv user records an audio file in the Story Tell Back phase and taps the cloud icon to upload the audio file to ROCC, it fails to upload.  A "fail" message appears and the ROCC does not receive the audio.
![Screenshot_20220730-162159](https://user-images.githubusercontent.com/98855936/181996641-d937965a-cf49-4497-a321-da3f8d96b73a.png)

**Comment by techteam25** [comment]
I requested more info from Robin, such as the size of the file and what phone (older or newer Android) was being used.   Seems this error is too large of a file was being sent to the webserver.

**Comment by techteam25** [comment]
after changing post max size, upload max size, max memory, timeouts in php.ini...  I found that nginx needed a line for max upload size as well.

**Comment by RobinRempel** [comment]
with the Aug 7 ROCC update and the rSPadv 1.1.2 debugging build, this issue seems to be resolved.  Closing the issue.
