### ISSUE TITLE
edit Story Tell Back help doc

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#67]
The Story Tell Back help doc needs editing, including the background title (it sort of has a double title, but they are not consistent)

**Comment by techteam25** [comment]
Help docs for Story Tell Back, Slide Tell Back and Remote Check have been adjusted to have spacing like the other phases and have the double title the same.

**Comment by RobinRempel** [comment]
For the rSPadv v1.1.2 debugger build, The inconsistent doubled title is corrected now, but the content of the help doc (red font) needs to be edited to reflect reality and then updated to black font.

**Comment by RobinRempel** [comment]
looks good in 1.1.3 debugger.  Closing.
