### ISSUE TITLE
Title slide text readability improvements

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#69]
Title slide text font needs to be reduced several points and the white letters need to have a black shadow/outline to make them more readable on varied-colored images.

**Comment by techteam25** [comment]
Send to Robin via email:
As I remember, this is directly the opposite of what was said we did the changes in SPadv1.1 for those in Cambodia (I think it was).  We eliminated the shadow/outline on the title and test slides.

Should we make this a setup option?  The user can turn it on or off as they desire?

**Comment by RobinRempel** [comment]
The title slide font issues need to be handled separately from the story text (subtitling).  The title slide does not have a blue rectangle background, so it needs the shadow/outline.  The font is too large for longer titles to fit within the frame. 
Perhaps later we can enhance the APK with a user mechanism for changing font features, but I'm a bit reluctant at this point to complicate the UI/UX.

**Comment by RobinRempel** [comment]
With the  rSPadv 1.1.2 build, this issues seems to be resolved. Closing the issue.
