### ISSUE TITLE
Firebase setup again

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#72]
get Firebase going for crash report and/or usage info

Does/should the registration info get sent to the server even if only ever used locally?
	Want to know how much is being used.   Or is/should this be firebase?
	Change Data Collection policy on store when this is captured

**Comment by RobinRempel** [comment]
A primary desire is to receive from SPadv phones that go online (only) **file names** of videos produced.  This bit of text data will give us the language info (ethnologue code), which story was translated, and what features the user was using.
