### ISSUE TITLE
Tyndale store?

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#73]
Need to create store for Tyndale Bible Translators and move app to it.

**Comment by techteam25** [comment]
Robin was wondering if Tyndale really wants their name on it for security of end users?  Will wait for her to decide.

**Comment by RobinRempel** [comment]
Maybe we could put **TyndaleBT** for the name. 
Rather than having the org name right under the app name, it would be helpful to have a brief explanation of what the app is/does -- something like "**Orally translate stories. Create localized videos. Publish songs.**"

**Comment by techteam25** [comment]
This is info that is needed, copy/pasted from Google:
Organization name
(The full, legal name of your organization. For example, Google LLC)

Organization address
Country
Organization phone number
Organization website
Contact name
Contact email address

I need all this info to start a store account.

**Comment by tkmeadows** [comment]
It was decided that they will leave it posted on TECH's store for now...
