### ISSUE TITLE
Data collection

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#83]
Data collection - Do we need to say that SPadv collects Registration info when it is submitted by the user? Is the software set up to collect video file names of videos produced by users when/if their phone is online? (SIL's version of SP was set up this way and was the primary data collection strategy to learn how much the app was being utilized.)

**Comment by techteam25** [comment]
Proposed/Draft statement for Data Collection:
Data is collected when a "Remote" consultant is selected in the registration process.  It is used only for the remote consultant(s) to communicate and assist the translators.

@RobinRempel

**Comment by RobinRempel** [comment]
Also / Or ....
Data is collected whenever the user submits Registration info.  All the information that the user types into the Registration fields, plus phone type, is sent to SPapp.training@gmail.com .

Tim, I don't think we have this set up yet with Firebase, but perhaps at some point it might be helpful to collect files names (only) of videos that are produced (if/when those phones get online).

**Comment by tkmeadows** [comment]
Issue techteam25/SPadvR3#72 deals with getting firebase set back up...

**Comment by tkmeadows** [comment]
Ready for store/app update:
Data is collected whenever the user submits Registration info. All the information that the user types into the Registration fields, plus phone type, is sent to SPapp.training@gmail.com

**Comment by RobinRempel** [comment]
In looking on the play store for v2.2 I do not see this info displayed, but it must be there somewhere.  I'll let you close this issue when it is confirmed.  
@tkmeadows

**Comment by techteam25** [comment]
It is in the store under the "Data Safety" area.  Google has you answer questions then they display the info for you instead of using our text.
