### ISSUE TITLE
Record/play / pause / resume control interactions

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#84]
When the user is pausing the playback to record a short phrase in the LWC, they only have to tap the mic and the playback will auto pause. However, if the user taps the playback button to listen to the next phrase, the back translation recording gets stopped. This is not good. The back translation recording should just be auto paused when the playback button is tapped. The user should not need to always tap pause to pause for resume recording. The mechanism should be such that when any play button is tapped while the recording is taking place, the recording will auto pause (not auto stop) and the recording will resume next time the mic button is tapped.

**Comment by RobinRempel** [comment]
This bug is occurring in both the Voice Studio and the Slide Tell-Back phases.

**Comment by RobinRempel** [comment]
with the rSPadv 1.1.2 debugging build, this issue seems to be resolved.  I tested this on an Android 8 and 11 phone. Closing the issue.
