### ISSUE TITLE
update apps to read .bloomSource as well as .bloom files

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#85]
Rationale:
SP needs to handle template files in the form that Bloom now produces (as Bloom evolves).
Bloom now saves single-file books with .bloomSource extension.

Describe specific requirements for what you want to happen :
SP should be able to recognize and import .bloomSource files in addition to the current .bloom files.

Note: SP Resources site can continue to distribute .bloom files at this time. That's a wee bit simpler for SP users still doing file management to install their templates, and for their trainer.

Acceptance:
SP can import (scan) a set of templates with mixed file extensions - .bloom and .bloomSource

**Comment by techteam25** [comment]
@RobinRempel 
Have you tested this one?
