### ISSUE TITLE
Notification flag on story list

### ISSUE THREAD

**Issue by tkmeadows** [techteam25/SPadv#90]
Have a notification "dot" on a story in the list of templates downloaded so the SPadv user knows there is a message from or approval by the ROCC user waiting.

**Comment by J-Daniel-S** [comment]
I seem to have forgotten how to move this to the "In Progress" column which makes me feel silly.  I've started work on this

**Comment by techteam25** [comment]
You should just be able to click-and-drag it over.

**Comment by J-Daniel-S** [comment]
That's what I thought but for some reason it's not working.  My cursor turns into a circle with a line through it when I try to drag and drop
