### ISSUE TITLE
NonEnglish language phase bars not showing help icon

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#93]
In all of the non-English language interfaces, on the colored phase bars at the top of each screen, the Help icon (?) is too far to the right and cannot be accessed.  The nonEnglish phase names need to take up less space so as to not push off the Help icon.

**Comment by techteam25** [comment]
On my phone its moved over a little but still accessible.  Please give language you tried and model of phone. Proportions or width of screen may be a factor

**Comment by RobinRempel** [comment]
First Screenshot from Spanish UI on Moto G5 device. (Larger screen)

Second screenshot from Portuguese UI on Samsung J3. (Smaller screen)

In both cases, the UI is too wide to be able to access the Help icon

**Comment by raykaestner** [comment]
I have a tentative fix that gives a max width to the phase dropdown in order to leave room for the help button.  The screenshots below show a Nexus 4.0 inch and Nexus 4.7 inch phone.  If the sceen size is much smaller the help button would still not be visible.  How small a screen do we need to plan for?

![Image](https://user-images.githubusercontent.com/123203572/226439807-47870590-9ab1-45d5-9c1d-2ec5445e3304.png)



![Image](https://user-images.githubusercontent.com/123203572/226439868-e9d9e6e0-4c4c-403b-b09e-91bad61725c7.png)

**Comment by RobinRempel** [comment]
This looks good.  I don't know how narrow we need to go, but it seems to me that if more space needs to be created on the Phase Name bar, the phase icon and the phase name could be scooted over to the left to give more space to the dropdown menu button and the Help button.  
The Main Menu button (far left), even if it is close to the phase icon, it can still be functional/accessible for fat fingers since the phase icon is not a button.  
Test your fix by changing the UI language to non English.  For some reason, the non English UI's are losing access to the help button.

**Comment by raykaestner** [comment]
This is a classic translation problem - the reason it was having trouble with non English UI's is that they have longer phase names.  I was able to duplicate the problem in English by giving them longer phase names (as in the sample pictures)  Limiting the size of the drop down allowed there to be enough space for the help button.   I will double check with a non-English UI to make sure.  (I tried moving the icon over, but the layout rules for the toolbar are somewhat different and I don't fully understand them yet)

**Comment by raykaestner** [comment]
Here is a couple of screenshots from Spanish and Portugese that demonstrate the fix.


![Image](https://user-images.githubusercontent.com/123203572/226738410-8ab094d7-ae88-4f10-903b-87c431b2709c.png)



![Image](https://user-images.githubusercontent.com/123203572/226738437-3751b355-2757-4fa4-acb4-ca4390e86f4c.png)

**Comment by RobinRempel** [comment]
I think this can be ok.  For the phone on the top, it's not great, because it will be difficult for fat fingers to touch the help icon without activating the dropdown menu and without the frame of the phone getting in the way, but at least it's visible now.  The spacing on phone on the bottom is very good.  
I'd say let's go with this fix.  (The help icon is not a super popular button...)   
Thank you, Ray!!
