### ISSUE TITLE
Story Template titles and subtitles not visible if too long

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#96]
If the title of a Story on the Story Templates screen wraps to more than two lines, the third line (usually the Scripture reference) gets cut off and is not visible to the viewer.  The "box" holding the text should expand.  Same problem as in the Share phase.

**Comment by dharding1958** [comment]
Please supply a story number and language as an example. Haven't found one yet that goes past 2 lines.

**Comment by RobinRempel** [comment]
English #122
Spanish #250

**Comment by raykaestner** [comment]
![LongTemplateNames-New](https://user-images.githubusercontent.com/123203572/225375528-58bc19f3-53de-4fe9-a94e-e2ed6c942715.png)
![LongTemplateNames-Old](https://user-images.githubusercontent.com/123203572/225375581-40198485-dee8-47f8-9e4c-41c58e331e78.png)
![LongTemplateNames2-New](https://user-images.githubusercontent.com/123203572/225375633-5078f811-d8bd-40b8-a8f3-2ad3da4c69e7.png)
![LongTemplateNames2-Old](https://user-images.githubusercontent.com/123203572/225375669-e3467f4f-6d7a-4052-9135-711ceb826f0b.png)

Uploaded screenshots of a potential fix that expands the size of the items in the list to allow for an extra line.  The "old" ones are with the existing code to compare with the "new" ones with the potential fix to allow for comparison.

**Comment by RobinRempel** [comment]
I think the more spacious / spaced out UI looks best -- where there is potential for 4 lines of text if needed.  (There are no English titles that will go beyond 3 lines of text, but titles can get lengthened when translated into other languages.  Also, some other language scripts are bulkier than Roman letters, so having the extra space is good for better readability.)
