### ISSUE TITLE
Update Gateway Lg UI files

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#99]
I've made a google drive link which you can access via the Tech Page on the [StoryPublisher.website](https://sites.google.com/view/spadv-website/home?authuser=2). 
This [link](https://drive.google.com/drive/folders/1Ovv7_qDSTOjiM8WYlObnj7er8snkJsN7?usp=share_link) has folders for all the Gateway languages (**LWC**s - Languages of Wider Communication) in which we have UI resources translated.  (French, Spanish, Portuguese, Swahili, Bahasa etc).  
These LWC UI resource files include:  strings, HELP docs, and WordLinks.

French has almost all new help docs and new wordlinks
English has new wordlinks

If some LWCs do not have all the UI resources, then the app should show English UI as the default, for whatever is not available in the LWC.

**Comment by techteam25** [comment]
I think this is now duplicated in #105
